### ISSUE TITLE
Project Installation instructions are missing some steps.

### ISSUE THREAD

**Issue by 4812571** [Paradigm-Shift-Games/Voltz#56]
We should be guiding users to install rust via ``rustup``

We should probably also use some verbiage to indicate that they only need to do it if they don't already have it.

**Comment by Hexcede** [comment]
> We should be guiding users to install rust via `rustup`
> 
> We should probably also use some verbiage to indicate that they only need to do it if they don't already have it.

Rust is no longer a necessary dependency (also see my comment in #57)
