### ISSUE TITLE
Aftman should be installed via ``rust``

### ISSUE THREAD

**Issue by 4812571** [Paradigm-Shift-Games/Voltz#57]
I think we should guide our users to install aftman via rust - despite the significant file size of the Rust compiler, and the compilation times, I dramatically prefer having a console-only workflow for installation process to

**Comment by 4812571** [comment]
This only necessitates a change to our readme file.

**Comment by Hexcede** [comment]
> I think we should guide our users to install aftman via rust - despite the significant file size of the Rust compiler, and the compilation times, I dramatically prefer having a console-only workflow for installation process to

![image](https://user-images.githubusercontent.com/8394472/184586727-673678a2-d28f-4bac-947b-c8dac387ccfc.png)
